# This file is a template, and might need editing before it works on your project.
docker-build-master:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

docker-build:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master

deploy:
 image: 'gcloud-with-envsubst:latest'
 stage: deploy
 variables:
 DOCKER_IMAGE_TAG: 'eu.gcr.io/my-project/my-application:latest'
 script:
 # Authenticate with GKE
  - echo "$SERVICE_ACCOUNT_KEY" > key.json
  - gcloud auth activate-service-account --key-file=key.json
  - gcloud config set project my-project
  - gcloud config set container/cluster my-cluster
  - gcloud config set compute/zone europe-west2-a
  - gcloud container clusters get-credentials my-cluster --zone europe-west2-a# Do the deployment
  - cat kubernetes/my-application-deployment.yaml | envsubst | kubectl apply -f -environment:
 name: test
only:
  - master